// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: order_service/order_service.proto

package proto

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_order_service_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_order_service_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *IdRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Price struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wei           string                 `protobuf:"bytes,1,opt,name=wei,proto3" json:"wei,omitempty"`
	Eth           float32                `protobuf:"fixed32,2,opt,name=eth,proto3" json:"eth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Price) Reset() {
	*x = Price{}
	mi := &file_order_service_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_order_service_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *Price) GetWei() string {
	if x != nil {
		return x.Wei
	}
	return ""
}

func (x *Price) GetEth() float32 {
	if x != nil {
		return x.Eth
	}
	return 0
}

type PreviewRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductId        uint32                 `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Amount           uint32                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	CountryId        uint32                 `protobuf:"varint,3,opt,name=countryId,proto3" json:"countryId,omitempty"`
	CourierCompanyId uint32                 `protobuf:"varint,4,opt,name=courierCompanyId,proto3" json:"courierCompanyId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PreviewRequest) Reset() {
	*x = PreviewRequest{}
	mi := &file_order_service_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRequest) ProtoMessage() {}

func (x *PreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRequest.ProtoReflect.Descriptor instead.
func (*PreviewRequest) Descriptor() ([]byte, []int) {
	return file_order_service_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *PreviewRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *PreviewRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PreviewRequest) GetCountryId() uint32 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

func (x *PreviewRequest) GetCourierCompanyId() uint32 {
	if x != nil {
		return x.CourierCompanyId
	}
	return 0
}

type MyOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderInfoResponse   `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyOrdersResponse) Reset() {
	*x = MyOrdersResponse{}
	mi := &file_order_service_order_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyOrdersResponse) ProtoMessage() {}

func (x *MyOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_order_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyOrdersResponse.ProtoReflect.Descriptor instead.
func (*MyOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_service_order_service_proto_rawDescGZIP(), []int{3}
}

func (x *MyOrdersResponse) GetOrders() []*OrderInfoResponse {
	if x != nil {
		return x.Orders
	}
	return nil
}

type PreviewResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ProducerWalletAddress string                 `protobuf:"bytes,1,opt,name=producerWalletAddress,proto3" json:"producerWalletAddress,omitempty"`
	CourierWalletAddress  string                 `protobuf:"bytes,2,opt,name=courierWalletAddress,proto3" json:"courierWalletAddress,omitempty"`
	ProductsPrice         *Price                 `protobuf:"bytes,3,opt,name=productsPrice,proto3" json:"productsPrice,omitempty"`
	DeliveryPrice         *Price                 `protobuf:"bytes,4,opt,name=deliveryPrice,proto3" json:"deliveryPrice,omitempty"`
	TotalPrice            *Price                 `protobuf:"bytes,5,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	DeliveryDate          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deliveryDate,proto3" json:"deliveryDate,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PreviewResponse) Reset() {
	*x = PreviewResponse{}
	mi := &file_order_service_order_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewResponse) ProtoMessage() {}

func (x *PreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_order_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewResponse.ProtoReflect.Descriptor instead.
func (*PreviewResponse) Descriptor() ([]byte, []int) {
	return file_order_service_order_service_proto_rawDescGZIP(), []int{4}
}

func (x *PreviewResponse) GetProducerWalletAddress() string {
	if x != nil {
		return x.ProducerWalletAddress
	}
	return ""
}

func (x *PreviewResponse) GetCourierWalletAddress() string {
	if x != nil {
		return x.CourierWalletAddress
	}
	return ""
}

func (x *PreviewResponse) GetProductsPrice() *Price {
	if x != nil {
		return x.ProductsPrice
	}
	return nil
}

func (x *PreviewResponse) GetDeliveryPrice() *Price {
	if x != nil {
		return x.DeliveryPrice
	}
	return nil
}

func (x *PreviewResponse) GetTotalPrice() *Price {
	if x != nil {
		return x.TotalPrice
	}
	return nil
}

func (x *PreviewResponse) GetDeliveryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveryDate
	}
	return nil
}

type OrderRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuthToken        string                 `protobuf:"bytes,1,opt,name=authToken,proto3" json:"authToken,omitempty"`
	ProductId        uint32                 `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Amount           uint32                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CountryId        uint32                 `protobuf:"varint,4,opt,name=countryId,proto3" json:"countryId,omitempty"`
	City             string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode       string                 `protobuf:"bytes,6,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	CourierCompanyId uint32                 `protobuf:"varint,7,opt,name=courierCompanyId,proto3" json:"courierCompanyId,omitempty"`
	WalletPrivateKey string                 `protobuf:"bytes,8,opt,name=walletPrivateKey,proto3" json:"walletPrivateKey,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_order_service_order_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_order_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_order_service_order_service_proto_rawDescGZIP(), []int{5}
}

func (x *OrderRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *OrderRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderRequest) GetCountryId() uint32 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

func (x *OrderRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *OrderRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *OrderRequest) GetCourierCompanyId() uint32 {
	if x != nil {
		return x.CourierCompanyId
	}
	return 0
}

func (x *OrderRequest) GetWalletPrivateKey() string {
	if x != nil {
		return x.WalletPrivateKey
	}
	return ""
}

type OrderResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductsPaymentHex string                 `protobuf:"bytes,2,opt,name=productsPaymentHex,proto3" json:"productsPaymentHex,omitempty"`
	DeliveryPaymentHex string                 `protobuf:"bytes,3,opt,name=deliveryPaymentHex,proto3" json:"deliveryPaymentHex,omitempty"`
	DeliveryDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deliveryDate,proto3" json:"deliveryDate,omitempty"`
	Price              *Price                 `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_order_service_order_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_order_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_order_service_order_service_proto_rawDescGZIP(), []int{6}
}

func (x *OrderResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderResponse) GetProductsPaymentHex() string {
	if x != nil {
		return x.ProductsPaymentHex
	}
	return ""
}

func (x *OrderResponse) GetDeliveryPaymentHex() string {
	if x != nil {
		return x.DeliveryPaymentHex
	}
	return ""
}

func (x *OrderResponse) GetDeliveryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveryDate
	}
	return nil
}

func (x *OrderResponse) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

type OrderInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId          uint32                 `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Amount             uint32                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CountryId          uint32                 `protobuf:"varint,4,opt,name=countryId,proto3" json:"countryId,omitempty"`
	City               string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode         string                 `protobuf:"bytes,6,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	CourierCompanyId   uint32                 `protobuf:"varint,7,opt,name=courierCompanyId,proto3" json:"courierCompanyId,omitempty"`
	ProductsPaymentHex string                 `protobuf:"bytes,8,opt,name=productsPaymentHex,proto3" json:"productsPaymentHex,omitempty"`
	DeliveryPaymentHex string                 `protobuf:"bytes,9,opt,name=deliveryPaymentHex,proto3" json:"deliveryPaymentHex,omitempty"`
	DeliveryDate       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deliveryDate,proto3" json:"deliveryDate,omitempty"`
	Delivered          bool                   `protobuf:"varint,11,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Price              *Price                 `protobuf:"bytes,12,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OrderInfoResponse) Reset() {
	*x = OrderInfoResponse{}
	mi := &file_order_service_order_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfoResponse) ProtoMessage() {}

func (x *OrderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_order_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfoResponse.ProtoReflect.Descriptor instead.
func (*OrderInfoResponse) Descriptor() ([]byte, []int) {
	return file_order_service_order_service_proto_rawDescGZIP(), []int{7}
}

func (x *OrderInfoResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfoResponse) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderInfoResponse) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderInfoResponse) GetCountryId() uint32 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

func (x *OrderInfoResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *OrderInfoResponse) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *OrderInfoResponse) GetCourierCompanyId() uint32 {
	if x != nil {
		return x.CourierCompanyId
	}
	return 0
}

func (x *OrderInfoResponse) GetProductsPaymentHex() string {
	if x != nil {
		return x.ProductsPaymentHex
	}
	return ""
}

func (x *OrderInfoResponse) GetDeliveryPaymentHex() string {
	if x != nil {
		return x.DeliveryPaymentHex
	}
	return ""
}

func (x *OrderInfoResponse) GetDeliveryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveryDate
	}
	return nil
}

func (x *OrderInfoResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *OrderInfoResponse) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

type CountriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countries     []*Country             `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountriesResponse) Reset() {
	*x = CountriesResponse{}
	mi := &file_order_service_order_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountriesResponse) ProtoMessage() {}

func (x *CountriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_order_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountriesResponse.ProtoReflect.Descriptor instead.
func (*CountriesResponse) Descriptor() ([]byte, []int) {
	return file_order_service_order_service_proto_rawDescGZIP(), []int{8}
}

func (x *CountriesResponse) GetCountries() []*Country {
	if x != nil {
		return x.Countries
	}
	return nil
}

type Country struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Country) Reset() {
	*x = Country{}
	mi := &file_order_service_order_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_order_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_order_service_order_service_proto_rawDescGZIP(), []int{9}
}

func (x *Country) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CouriersForCountryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Companies     []*CourierCompany      `protobuf:"bytes,1,rep,name=companies,proto3" json:"companies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouriersForCountryResponse) Reset() {
	*x = CouriersForCountryResponse{}
	mi := &file_order_service_order_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouriersForCountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouriersForCountryResponse) ProtoMessage() {}

func (x *CouriersForCountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_order_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouriersForCountryResponse.ProtoReflect.Descriptor instead.
func (*CouriersForCountryResponse) Descriptor() ([]byte, []int) {
	return file_order_service_order_service_proto_rawDescGZIP(), []int{10}
}

func (x *CouriersForCountryResponse) GetCompanies() []*CourierCompany {
	if x != nil {
		return x.Companies
	}
	return nil
}

type CourierCompany struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DeliveryPrice *Price                 `protobuf:"bytes,3,opt,name=deliveryPrice,proto3" json:"deliveryPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourierCompany) Reset() {
	*x = CourierCompany{}
	mi := &file_order_service_order_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourierCompany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierCompany) ProtoMessage() {}

func (x *CourierCompany) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_order_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierCompany.ProtoReflect.Descriptor instead.
func (*CourierCompany) Descriptor() ([]byte, []int) {
	return file_order_service_order_service_proto_rawDescGZIP(), []int{11}
}

func (x *CourierCompany) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CourierCompany) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CourierCompany) GetDeliveryPrice() *Price {
	if x != nil {
		return x.DeliveryPrice
	}
	return nil
}

var File_order_service_order_service_proto protoreflect.FileDescriptor

const file_order_service_order_service_proto_rawDesc = "" +
	"\n" +
	"!order_service/order_service.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"+\n" +
	"\x05Price\x12\x10\n" +
	"\x03wei\x18\x01 \x01(\tR\x03wei\x12\x10\n" +
	"\x03eth\x18\x02 \x01(\x02R\x03eth\"\x90\x01\n" +
	"\x0ePreviewRequest\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\rR\tproductId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\rR\x06amount\x12\x1c\n" +
	"\tcountryId\x18\x03 \x01(\rR\tcountryId\x12*\n" +
	"\x10courierCompanyId\x18\x04 \x01(\rR\x10courierCompanyId\"A\n" +
	"\x10MyOrdersResponse\x12-\n" +
	"\x06orders\x18\x01 \x03(\v2\x15.pb.OrderInfoResponseR\x06orders\"\xc8\x02\n" +
	"\x0fPreviewResponse\x124\n" +
	"\x15producerWalletAddress\x18\x01 \x01(\tR\x15producerWalletAddress\x122\n" +
	"\x14courierWalletAddress\x18\x02 \x01(\tR\x14courierWalletAddress\x12/\n" +
	"\rproductsPrice\x18\x03 \x01(\v2\t.pb.PriceR\rproductsPrice\x12/\n" +
	"\rdeliveryPrice\x18\x04 \x01(\v2\t.pb.PriceR\rdeliveryPrice\x12)\n" +
	"\n" +
	"totalPrice\x18\x05 \x01(\v2\t.pb.PriceR\n" +
	"totalPrice\x12>\n" +
	"\fdeliveryDate\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fdeliveryDate\"\x8c\x02\n" +
	"\fOrderRequest\x12\x1c\n" +
	"\tauthToken\x18\x01 \x01(\tR\tauthToken\x12\x1c\n" +
	"\tproductId\x18\x02 \x01(\rR\tproductId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\rR\x06amount\x12\x1c\n" +
	"\tcountryId\x18\x04 \x01(\rR\tcountryId\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1e\n" +
	"\n" +
	"postalCode\x18\x06 \x01(\tR\n" +
	"postalCode\x12*\n" +
	"\x10courierCompanyId\x18\a \x01(\rR\x10courierCompanyId\x12*\n" +
	"\x10walletPrivateKey\x18\b \x01(\tR\x10walletPrivateKey\"\xe0\x01\n" +
	"\rOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12.\n" +
	"\x12productsPaymentHex\x18\x02 \x01(\tR\x12productsPaymentHex\x12.\n" +
	"\x12deliveryPaymentHex\x18\x03 \x01(\tR\x12deliveryPaymentHex\x12>\n" +
	"\fdeliveryDate\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fdeliveryDate\x12\x1f\n" +
	"\x05price\x18\x05 \x01(\v2\t.pb.PriceR\x05price\"\xb6\x03\n" +
	"\x11OrderInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1c\n" +
	"\tproductId\x18\x02 \x01(\rR\tproductId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\rR\x06amount\x12\x1c\n" +
	"\tcountryId\x18\x04 \x01(\rR\tcountryId\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1e\n" +
	"\n" +
	"postalCode\x18\x06 \x01(\tR\n" +
	"postalCode\x12*\n" +
	"\x10courierCompanyId\x18\a \x01(\rR\x10courierCompanyId\x12.\n" +
	"\x12productsPaymentHex\x18\b \x01(\tR\x12productsPaymentHex\x12.\n" +
	"\x12deliveryPaymentHex\x18\t \x01(\tR\x12deliveryPaymentHex\x12>\n" +
	"\fdeliveryDate\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\fdeliveryDate\x12\x1c\n" +
	"\tdelivered\x18\v \x01(\bR\tdelivered\x12\x1f\n" +
	"\x05price\x18\f \x01(\v2\t.pb.PriceR\x05price\">\n" +
	"\x11CountriesResponse\x12)\n" +
	"\tcountries\x18\x01 \x03(\v2\v.pb.CountryR\tcountries\"-\n" +
	"\aCountry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"N\n" +
	"\x1aCouriersForCountryResponse\x120\n" +
	"\tcompanies\x18\x01 \x03(\v2\x12.pb.CourierCompanyR\tcompanies\"e\n" +
	"\x0eCourierCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\rdeliveryPrice\x18\x03 \x01(\v2\t.pb.PriceR\rdeliveryPrice2\xbd\x02\n" +
	"\fOrderService\x12G\n" +
	"\aPreview\x12\x12.pb.PreviewRequest\x1a\x13.pb.PreviewResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/preview\x12?\n" +
	"\x05Order\x12\x10.pb.OrderRequest\x1a\x11.pb.OrderResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/order\x12@\n" +
	"\x04Info\x12\r.pb.IdRequest\x1a\x15.pb.OrderInfoResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/info/{id}\x12a\n" +
	"\bMyOrders\x12\x16.google.protobuf.Empty\x1a\x14.pb.MyOrdersResponse\"'\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/me/orders2\xc8\x01\n" +
	"\x0fResourceService\x12N\n" +
	"\tCountries\x12\x16.google.protobuf.Empty\x1a\x15.pb.CountriesResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/countries\x12e\n" +
	"\x12CouriersForCountry\x12\r.pb.IdRequest\x1a\x1e.pb.CouriersForCountryResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/countries/{id}/couriersB\x0fZ\rgateway/protob\x06proto3"

var (
	file_order_service_order_service_proto_rawDescOnce sync.Once
	file_order_service_order_service_proto_rawDescData []byte
)

func file_order_service_order_service_proto_rawDescGZIP() []byte {
	file_order_service_order_service_proto_rawDescOnce.Do(func() {
		file_order_service_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_service_order_service_proto_rawDesc), len(file_order_service_order_service_proto_rawDesc)))
	})
	return file_order_service_order_service_proto_rawDescData
}

var file_order_service_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_order_service_order_service_proto_goTypes = []any{
	(*IdRequest)(nil),                  // 0: pb.IdRequest
	(*Price)(nil),                      // 1: pb.Price
	(*PreviewRequest)(nil),             // 2: pb.PreviewRequest
	(*MyOrdersResponse)(nil),           // 3: pb.MyOrdersResponse
	(*PreviewResponse)(nil),            // 4: pb.PreviewResponse
	(*OrderRequest)(nil),               // 5: pb.OrderRequest
	(*OrderResponse)(nil),              // 6: pb.OrderResponse
	(*OrderInfoResponse)(nil),          // 7: pb.OrderInfoResponse
	(*CountriesResponse)(nil),          // 8: pb.CountriesResponse
	(*Country)(nil),                    // 9: pb.Country
	(*CouriersForCountryResponse)(nil), // 10: pb.CouriersForCountryResponse
	(*CourierCompany)(nil),             // 11: pb.CourierCompany
	(*timestamppb.Timestamp)(nil),      // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 13: google.protobuf.Empty
}
var file_order_service_order_service_proto_depIdxs = []int32{
	7,  // 0: pb.MyOrdersResponse.orders:type_name -> pb.OrderInfoResponse
	1,  // 1: pb.PreviewResponse.productsPrice:type_name -> pb.Price
	1,  // 2: pb.PreviewResponse.deliveryPrice:type_name -> pb.Price
	1,  // 3: pb.PreviewResponse.totalPrice:type_name -> pb.Price
	12, // 4: pb.PreviewResponse.deliveryDate:type_name -> google.protobuf.Timestamp
	12, // 5: pb.OrderResponse.deliveryDate:type_name -> google.protobuf.Timestamp
	1,  // 6: pb.OrderResponse.price:type_name -> pb.Price
	12, // 7: pb.OrderInfoResponse.deliveryDate:type_name -> google.protobuf.Timestamp
	1,  // 8: pb.OrderInfoResponse.price:type_name -> pb.Price
	9,  // 9: pb.CountriesResponse.countries:type_name -> pb.Country
	11, // 10: pb.CouriersForCountryResponse.companies:type_name -> pb.CourierCompany
	1,  // 11: pb.CourierCompany.deliveryPrice:type_name -> pb.Price
	2,  // 12: pb.OrderService.Preview:input_type -> pb.PreviewRequest
	5,  // 13: pb.OrderService.Order:input_type -> pb.OrderRequest
	0,  // 14: pb.OrderService.Info:input_type -> pb.IdRequest
	13, // 15: pb.OrderService.MyOrders:input_type -> google.protobuf.Empty
	13, // 16: pb.ResourceService.Countries:input_type -> google.protobuf.Empty
	0,  // 17: pb.ResourceService.CouriersForCountry:input_type -> pb.IdRequest
	4,  // 18: pb.OrderService.Preview:output_type -> pb.PreviewResponse
	6,  // 19: pb.OrderService.Order:output_type -> pb.OrderResponse
	7,  // 20: pb.OrderService.Info:output_type -> pb.OrderInfoResponse
	3,  // 21: pb.OrderService.MyOrders:output_type -> pb.MyOrdersResponse
	8,  // 22: pb.ResourceService.Countries:output_type -> pb.CountriesResponse
	10, // 23: pb.ResourceService.CouriersForCountry:output_type -> pb.CouriersForCountryResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_order_service_order_service_proto_init() }
func file_order_service_order_service_proto_init() {
	if File_order_service_order_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_service_order_service_proto_rawDesc), len(file_order_service_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_order_service_order_service_proto_goTypes,
		DependencyIndexes: file_order_service_order_service_proto_depIdxs,
		MessageInfos:      file_order_service_order_service_proto_msgTypes,
	}.Build()
	File_order_service_order_service_proto = out.File
	file_order_service_order_service_proto_goTypes = nil
	file_order_service_order_service_proto_depIdxs = nil
}
