// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: product_service/product_service.proto

package proto

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ParentCategoryId *int64                 `protobuf:"varint,4,opt,name=parent_category_id,json=parentCategoryId,proto3,oneof" json:"parent_category_id,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_product_service_product_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Category) GetParentCategoryId() int64 {
	if x != nil && x.ParentCategoryId != nil {
		return *x.ParentCategoryId
	}
	return 0
}

func (x *Category) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Category) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Sku           string                 `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	StockQuantity int32                  `protobuf:"varint,6,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	CategoryId    *int64                 `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,10,opt,name=attributes,proto3,oneof" json:"attributes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_service_product_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetStockQuantity() int32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *Product) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *Product) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *Product) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Product) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_product_service_product_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request message for pagination
type PageInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfoRequest) Reset() {
	*x = PageInfoRequest{}
	mi := &file_product_service_product_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfoRequest) ProtoMessage() {}

func (x *PageInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfoRequest.ProtoReflect.Descriptor instead.
func (*PageInfoRequest) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{3}
}

func (x *PageInfoRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageInfoRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response message for pagination
type PageInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalSize     int32                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfoResponse) Reset() {
	*x = PageInfoResponse{}
	mi := &file_product_service_product_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfoResponse) ProtoMessage() {}

func (x *PageInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfoResponse.ProtoReflect.Descriptor instead.
func (*PageInfoResponse) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{4}
}

func (x *PageInfoResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *PageInfoResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// Represents an empty request or response.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_product_service_product_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{5}
}

// Represents a request with a single ID.
type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_product_service_product_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{6}
}

func (x *IdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Represents a response indicating success.
type SuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessResponse) Reset() {
	*x = SuccessResponse{}
	mi := &file_product_service_product_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponse) ProtoMessage() {}

func (x *SuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponse.ProtoReflect.Descriptor instead.
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{7}
}

func (x *SuccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SuccessResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type GetProductDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductDetailsRequest) Reset() {
	*x = GetProductDetailsRequest{}
	mi := &file_product_service_product_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailsRequest) ProtoMessage() {}

func (x *GetProductDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetProductDetailsRequest) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetProductDetailsRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProductDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductDetailsResponse) Reset() {
	*x = GetProductDetailsResponse{}
	mi := &file_product_service_product_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailsResponse) ProtoMessage() {}

func (x *GetProductDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetProductDetailsResponse) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetProductDetailsResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsInternalRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PageInfo        *PageInfoRequest       `protobuf:"bytes,1,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	CategoryId      *int64                 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	ProductIds      []int64                `protobuf:"varint,3,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	IncludeInactive *bool                  `protobuf:"varint,4,opt,name=include_inactive,json=includeInactive,proto3,oneof" json:"include_inactive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListProductsInternalRequest) Reset() {
	*x = ListProductsInternalRequest{}
	mi := &file_product_service_product_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsInternalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsInternalRequest) ProtoMessage() {}

func (x *ListProductsInternalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsInternalRequest.ProtoReflect.Descriptor instead.
func (*ListProductsInternalRequest) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListProductsInternalRequest) GetPageInfo() *PageInfoRequest {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *ListProductsInternalRequest) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *ListProductsInternalRequest) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *ListProductsInternalRequest) GetIncludeInactive() bool {
	if x != nil && x.IncludeInactive != nil {
		return *x.IncludeInactive
	}
	return false
}

type ListProductsInternalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	PageInfo      *PageInfoResponse      `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsInternalResponse) Reset() {
	*x = ListProductsInternalResponse{}
	mi := &file_product_service_product_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsInternalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsInternalResponse) ProtoMessage() {}

func (x *ListProductsInternalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsInternalResponse.ProtoReflect.Descriptor instead.
func (*ListProductsInternalResponse) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListProductsInternalResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsInternalResponse) GetPageInfo() *PageInfoResponse {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type StockUpdateItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	QuantityChange int32                  `protobuf:"varint,2,opt,name=quantity_change,json=quantityChange,proto3" json:"quantity_change,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StockUpdateItem) Reset() {
	*x = StockUpdateItem{}
	mi := &file_product_service_product_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockUpdateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockUpdateItem) ProtoMessage() {}

func (x *StockUpdateItem) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockUpdateItem.ProtoReflect.Descriptor instead.
func (*StockUpdateItem) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{12}
}

func (x *StockUpdateItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *StockUpdateItem) GetQuantityChange() int32 {
	if x != nil {
		return x.QuantityChange
	}
	return 0
}

type UpdateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockUpdateItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	OrderId       *string                `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3,oneof" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_product_service_product_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateStockRequest) GetItems() []*StockUpdateItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UpdateStockRequest) GetOrderId() string {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return ""
}

type UpdateStockResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UpdatedProducts []*Product             `protobuf:"bytes,1,rep,name=updated_products,json=updatedProducts,proto3" json:"updated_products,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateStockResponse) Reset() {
	*x = UpdateStockResponse{}
	mi := &file_product_service_product_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockResponse) ProtoMessage() {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateStockResponse) GetUpdatedProducts() []*Product {
	if x != nil {
		return x.UpdatedProducts
	}
	return nil
}

type GetCategoryDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryDetailsRequest) Reset() {
	*x = GetCategoryDetailsRequest{}
	mi := &file_product_service_product_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryDetailsRequest) ProtoMessage() {}

func (x *GetCategoryDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryDetailsRequest) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetCategoryDetailsRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type GetCategoryDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryDetailsResponse) Reset() {
	*x = GetCategoryDetailsResponse{}
	mi := &file_product_service_product_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryDetailsResponse) ProtoMessage() {}

func (x *GetCategoryDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryDetailsResponse) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetCategoryDetailsResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type ListCategoriesInternalRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PageInfo         *PageInfoRequest       `protobuf:"bytes,1,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	ParentCategoryId *int64                 `protobuf:"varint,2,opt,name=parent_category_id,json=parentCategoryId,proto3,oneof" json:"parent_category_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListCategoriesInternalRequest) Reset() {
	*x = ListCategoriesInternalRequest{}
	mi := &file_product_service_product_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesInternalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesInternalRequest) ProtoMessage() {}

func (x *ListCategoriesInternalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesInternalRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesInternalRequest) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListCategoriesInternalRequest) GetPageInfo() *PageInfoRequest {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *ListCategoriesInternalRequest) GetParentCategoryId() int64 {
	if x != nil && x.ParentCategoryId != nil {
		return *x.ParentCategoryId
	}
	return 0
}

type ListCategoriesInternalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	PageInfo      *PageInfoResponse      `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesInternalResponse) Reset() {
	*x = ListCategoriesInternalResponse{}
	mi := &file_product_service_product_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesInternalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesInternalResponse) ProtoMessage() {}

func (x *ListCategoriesInternalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesInternalResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesInternalResponse) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{18}
}

func (x *ListCategoriesInternalResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ListCategoriesInternalResponse) GetPageInfo() *PageInfoResponse {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type ProductAvailabilityItemInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductId        int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	RequiredQuantity int32                  `protobuf:"varint,2,opt,name=required_quantity,json=requiredQuantity,proto3" json:"required_quantity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProductAvailabilityItemInput) Reset() {
	*x = ProductAvailabilityItemInput{}
	mi := &file_product_service_product_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAvailabilityItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAvailabilityItemInput) ProtoMessage() {}

func (x *ProductAvailabilityItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAvailabilityItemInput.ProtoReflect.Descriptor instead.
func (*ProductAvailabilityItemInput) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{19}
}

func (x *ProductAvailabilityItemInput) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductAvailabilityItemInput) GetRequiredQuantity() int32 {
	if x != nil {
		return x.RequiredQuantity
	}
	return 0
}

type CheckProductsAvailabilityRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Items         []*ProductAvailabilityItemInput `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckProductsAvailabilityRequest) Reset() {
	*x = CheckProductsAvailabilityRequest{}
	mi := &file_product_service_product_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProductsAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProductsAvailabilityRequest) ProtoMessage() {}

func (x *CheckProductsAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProductsAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckProductsAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{20}
}

func (x *CheckProductsAvailabilityRequest) GetItems() []*ProductAvailabilityItemInput {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProductAvailabilityStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProductId          int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	IsAvailable        bool                   `protobuf:"varint,2,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	AvailableQuantity  int32                  `protobuf:"varint,3,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	CurrentPrice       float64                `protobuf:"fixed64,4,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	Name               string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	ReasonNotAvailable *string                `protobuf:"bytes,6,opt,name=reason_not_available,json=reasonNotAvailable,proto3,oneof" json:"reason_not_available,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProductAvailabilityStatus) Reset() {
	*x = ProductAvailabilityStatus{}
	mi := &file_product_service_product_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAvailabilityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAvailabilityStatus) ProtoMessage() {}

func (x *ProductAvailabilityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAvailabilityStatus.ProtoReflect.Descriptor instead.
func (*ProductAvailabilityStatus) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{21}
}

func (x *ProductAvailabilityStatus) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductAvailabilityStatus) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *ProductAvailabilityStatus) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *ProductAvailabilityStatus) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *ProductAvailabilityStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductAvailabilityStatus) GetReasonNotAvailable() string {
	if x != nil && x.ReasonNotAvailable != nil {
		return *x.ReasonNotAvailable
	}
	return ""
}

type CheckProductsAvailabilityResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Statuses      []*ProductAvailabilityStatus `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckProductsAvailabilityResponse) Reset() {
	*x = CheckProductsAvailabilityResponse{}
	mi := &file_product_service_product_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProductsAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProductsAvailabilityResponse) ProtoMessage() {}

func (x *CheckProductsAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_product_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProductsAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckProductsAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_product_service_product_service_proto_rawDescGZIP(), []int{22}
}

func (x *CheckProductsAvailabilityResponse) GetStatuses() []*ProductAvailabilityStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_product_service_product_service_proto protoreflect.FileDescriptor

const file_product_service_product_service_proto_rawDesc = "" +
	"\n" +
	"%product_service/product_service.proto\x12\n" +
	"product.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa5\x02\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x121\n" +
	"\x12parent_category_id\x18\x04 \x01(\x03H\x01R\x10parentCategoryId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\x15\n" +
	"\x13_parent_category_id\"\xf9\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12%\n" +
	"\x0estock_quantity\x18\x06 \x01(\x05R\rstockQuantity\x12$\n" +
	"\vcategory_id\x18\a \x01(\x03H\x01R\n" +
	"categoryId\x88\x01\x01\x12 \n" +
	"\timage_url\x18\b \x01(\tH\x02R\bimageUrl\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12<\n" +
	"\n" +
	"attributes\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructH\x03R\n" +
	"attributes\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_category_idB\f\n" +
	"\n" +
	"_image_urlB\r\n" +
	"\v_attributes\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x0fPageInfoRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"Y\n" +
	"\x10PageInfoResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x05R\ttotalSize\"\a\n" +
	"\x05Empty\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"V\n" +
	"\x0fSuccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"9\n" +
	"\x18GetProductDetailsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"J\n" +
	"\x19GetProductDetailsResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"\xf3\x01\n" +
	"\x1bListProductsInternalRequest\x128\n" +
	"\tpage_info\x18\x01 \x01(\v2\x1b.product.v1.PageInfoRequestR\bpageInfo\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\x03H\x00R\n" +
	"categoryId\x88\x01\x01\x12\x1f\n" +
	"\vproduct_ids\x18\x03 \x03(\x03R\n" +
	"productIds\x12.\n" +
	"\x10include_inactive\x18\x04 \x01(\bH\x01R\x0fincludeInactive\x88\x01\x01B\x0e\n" +
	"\f_category_idB\x13\n" +
	"\x11_include_inactive\"\x8a\x01\n" +
	"\x1cListProductsInternalResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.product.v1.ProductR\bproducts\x129\n" +
	"\tpage_info\x18\x02 \x01(\v2\x1c.product.v1.PageInfoResponseR\bpageInfo\"Y\n" +
	"\x0fStockUpdateItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12'\n" +
	"\x0fquantity_change\x18\x02 \x01(\x05R\x0equantityChange\"t\n" +
	"\x12UpdateStockRequest\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.product.v1.StockUpdateItemR\x05items\x12\x1e\n" +
	"\border_id\x18\x02 \x01(\tH\x00R\aorderId\x88\x01\x01B\v\n" +
	"\t_order_id\"U\n" +
	"\x13UpdateStockResponse\x12>\n" +
	"\x10updated_products\x18\x01 \x03(\v2\x13.product.v1.ProductR\x0fupdatedProducts\"<\n" +
	"\x19GetCategoryDetailsRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\"N\n" +
	"\x1aGetCategoryDetailsResponse\x120\n" +
	"\bcategory\x18\x01 \x01(\v2\x14.product.v1.CategoryR\bcategory\"\xa3\x01\n" +
	"\x1dListCategoriesInternalRequest\x128\n" +
	"\tpage_info\x18\x01 \x01(\v2\x1b.product.v1.PageInfoRequestR\bpageInfo\x121\n" +
	"\x12parent_category_id\x18\x02 \x01(\x03H\x00R\x10parentCategoryId\x88\x01\x01B\x15\n" +
	"\x13_parent_category_id\"\x91\x01\n" +
	"\x1eListCategoriesInternalResponse\x124\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x14.product.v1.CategoryR\n" +
	"categories\x129\n" +
	"\tpage_info\x18\x02 \x01(\v2\x1c.product.v1.PageInfoResponseR\bpageInfo\"j\n" +
	"\x1cProductAvailabilityItemInput\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12+\n" +
	"\x11required_quantity\x18\x02 \x01(\x05R\x10requiredQuantity\"b\n" +
	" CheckProductsAvailabilityRequest\x12>\n" +
	"\x05items\x18\x01 \x03(\v2(.product.v1.ProductAvailabilityItemInputR\x05items\"\x95\x02\n" +
	"\x19ProductAvailabilityStatus\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12!\n" +
	"\fis_available\x18\x02 \x01(\bR\visAvailable\x12-\n" +
	"\x12available_quantity\x18\x03 \x01(\x05R\x11availableQuantity\x12#\n" +
	"\rcurrent_price\x18\x04 \x01(\x01R\fcurrentPrice\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x125\n" +
	"\x14reason_not_available\x18\x06 \x01(\tH\x00R\x12reasonNotAvailable\x88\x01\x01B\x17\n" +
	"\x15_reason_not_available\"f\n" +
	"!CheckProductsAvailabilityResponse\x12A\n" +
	"\bstatuses\x18\x01 \x03(\v2%.product.v1.ProductAvailabilityStatusR\bstatuses2\xa9\x06\n" +
	"\x15ProductCatalogService\x12\x80\x01\n" +
	"\x11GetProductDetails\x12$.product.v1.GetProductDetailsRequest\x1a%.product.v1.GetProductDetailsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/products/{product_id}\x12|\n" +
	"\x14ListProductsInternal\x12'.product.v1.ListProductsInternalRequest\x1a(.product.v1.ListProductsInternalResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/products\x12a\n" +
	"\vUpdateStock\x12\x1e.product.v1.UpdateStockRequest\x1a\x1f.product.v1.UpdateStockResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/stock\x12\x86\x01\n" +
	"\x12GetCategoryDetails\x12%.product.v1.GetCategoryDetailsRequest\x1a&.product.v1.GetCategoryDetailsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/categories/{category_id}\x12\x84\x01\n" +
	"\x16ListCategoriesInternal\x12).product.v1.ListCategoriesInternalRequest\x1a*.product.v1.ListCategoriesInternalResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/categories\x12\x9b\x01\n" +
	"\x19CheckProductsAvailability\x12,.product.v1.CheckProductsAvailabilityRequest\x1a-.product.v1.CheckProductsAvailabilityResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/products/availabilityB\x0fZ\rgateway/protob\x06proto3"

var (
	file_product_service_product_service_proto_rawDescOnce sync.Once
	file_product_service_product_service_proto_rawDescData []byte
)

func file_product_service_product_service_proto_rawDescGZIP() []byte {
	file_product_service_product_service_proto_rawDescOnce.Do(func() {
		file_product_service_product_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_service_product_service_proto_rawDesc), len(file_product_service_product_service_proto_rawDesc)))
	})
	return file_product_service_product_service_proto_rawDescData
}

var file_product_service_product_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_product_service_product_service_proto_goTypes = []any{
	(*Category)(nil),                          // 0: product.v1.Category
	(*Product)(nil),                           // 1: product.v1.Product
	(*ErrorResponse)(nil),                     // 2: product.v1.ErrorResponse
	(*PageInfoRequest)(nil),                   // 3: product.v1.PageInfoRequest
	(*PageInfoResponse)(nil),                  // 4: product.v1.PageInfoResponse
	(*Empty)(nil),                             // 5: product.v1.Empty
	(*IdRequest)(nil),                         // 6: product.v1.IdRequest
	(*SuccessResponse)(nil),                   // 7: product.v1.SuccessResponse
	(*GetProductDetailsRequest)(nil),          // 8: product.v1.GetProductDetailsRequest
	(*GetProductDetailsResponse)(nil),         // 9: product.v1.GetProductDetailsResponse
	(*ListProductsInternalRequest)(nil),       // 10: product.v1.ListProductsInternalRequest
	(*ListProductsInternalResponse)(nil),      // 11: product.v1.ListProductsInternalResponse
	(*StockUpdateItem)(nil),                   // 12: product.v1.StockUpdateItem
	(*UpdateStockRequest)(nil),                // 13: product.v1.UpdateStockRequest
	(*UpdateStockResponse)(nil),               // 14: product.v1.UpdateStockResponse
	(*GetCategoryDetailsRequest)(nil),         // 15: product.v1.GetCategoryDetailsRequest
	(*GetCategoryDetailsResponse)(nil),        // 16: product.v1.GetCategoryDetailsResponse
	(*ListCategoriesInternalRequest)(nil),     // 17: product.v1.ListCategoriesInternalRequest
	(*ListCategoriesInternalResponse)(nil),    // 18: product.v1.ListCategoriesInternalResponse
	(*ProductAvailabilityItemInput)(nil),      // 19: product.v1.ProductAvailabilityItemInput
	(*CheckProductsAvailabilityRequest)(nil),  // 20: product.v1.CheckProductsAvailabilityRequest
	(*ProductAvailabilityStatus)(nil),         // 21: product.v1.ProductAvailabilityStatus
	(*CheckProductsAvailabilityResponse)(nil), // 22: product.v1.CheckProductsAvailabilityResponse
	(*timestamppb.Timestamp)(nil),             // 23: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                   // 24: google.protobuf.Struct
}
var file_product_service_product_service_proto_depIdxs = []int32{
	23, // 0: product.v1.Category.created_at:type_name -> google.protobuf.Timestamp
	23, // 1: product.v1.Category.updated_at:type_name -> google.protobuf.Timestamp
	24, // 2: product.v1.Product.attributes:type_name -> google.protobuf.Struct
	23, // 3: product.v1.Product.created_at:type_name -> google.protobuf.Timestamp
	23, // 4: product.v1.Product.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: product.v1.GetProductDetailsResponse.product:type_name -> product.v1.Product
	3,  // 6: product.v1.ListProductsInternalRequest.page_info:type_name -> product.v1.PageInfoRequest
	1,  // 7: product.v1.ListProductsInternalResponse.products:type_name -> product.v1.Product
	4,  // 8: product.v1.ListProductsInternalResponse.page_info:type_name -> product.v1.PageInfoResponse
	12, // 9: product.v1.UpdateStockRequest.items:type_name -> product.v1.StockUpdateItem
	1,  // 10: product.v1.UpdateStockResponse.updated_products:type_name -> product.v1.Product
	0,  // 11: product.v1.GetCategoryDetailsResponse.category:type_name -> product.v1.Category
	3,  // 12: product.v1.ListCategoriesInternalRequest.page_info:type_name -> product.v1.PageInfoRequest
	0,  // 13: product.v1.ListCategoriesInternalResponse.categories:type_name -> product.v1.Category
	4,  // 14: product.v1.ListCategoriesInternalResponse.page_info:type_name -> product.v1.PageInfoResponse
	19, // 15: product.v1.CheckProductsAvailabilityRequest.items:type_name -> product.v1.ProductAvailabilityItemInput
	21, // 16: product.v1.CheckProductsAvailabilityResponse.statuses:type_name -> product.v1.ProductAvailabilityStatus
	8,  // 17: product.v1.ProductCatalogService.GetProductDetails:input_type -> product.v1.GetProductDetailsRequest
	10, // 18: product.v1.ProductCatalogService.ListProductsInternal:input_type -> product.v1.ListProductsInternalRequest
	13, // 19: product.v1.ProductCatalogService.UpdateStock:input_type -> product.v1.UpdateStockRequest
	15, // 20: product.v1.ProductCatalogService.GetCategoryDetails:input_type -> product.v1.GetCategoryDetailsRequest
	17, // 21: product.v1.ProductCatalogService.ListCategoriesInternal:input_type -> product.v1.ListCategoriesInternalRequest
	20, // 22: product.v1.ProductCatalogService.CheckProductsAvailability:input_type -> product.v1.CheckProductsAvailabilityRequest
	9,  // 23: product.v1.ProductCatalogService.GetProductDetails:output_type -> product.v1.GetProductDetailsResponse
	11, // 24: product.v1.ProductCatalogService.ListProductsInternal:output_type -> product.v1.ListProductsInternalResponse
	14, // 25: product.v1.ProductCatalogService.UpdateStock:output_type -> product.v1.UpdateStockResponse
	16, // 26: product.v1.ProductCatalogService.GetCategoryDetails:output_type -> product.v1.GetCategoryDetailsResponse
	18, // 27: product.v1.ProductCatalogService.ListCategoriesInternal:output_type -> product.v1.ListCategoriesInternalResponse
	22, // 28: product.v1.ProductCatalogService.CheckProductsAvailability:output_type -> product.v1.CheckProductsAvailabilityResponse
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_product_service_product_service_proto_init() }
func file_product_service_product_service_proto_init() {
	if File_product_service_product_service_proto != nil {
		return
	}
	file_product_service_product_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_product_service_product_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_product_service_product_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_product_service_product_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_product_service_product_service_proto_msgTypes[13].OneofWrappers = []any{}
	file_product_service_product_service_proto_msgTypes[17].OneofWrappers = []any{}
	file_product_service_product_service_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_service_product_service_proto_rawDesc), len(file_product_service_product_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_service_product_service_proto_goTypes,
		DependencyIndexes: file_product_service_product_service_proto_depIdxs,
		MessageInfos:      file_product_service_product_service_proto_msgTypes,
	}.Build()
	File_product_service_product_service_proto = out.File
	file_product_service_product_service_proto_goTypes = nil
	file_product_service_product_service_proto_depIdxs = nil
}
